spring:
  application:
    name: rep-write
  thymeleaf:
    cache: false

aws:
  ssm:
    region: "ap-southeast-2"
  dynamodb:
    endpoint: "http://localhost:8000"
    region: "ap-southeast-2"

gemini:
  url: "https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite-preview:generateContent"

repwrite:
  admin:
    password: "pass"
